### ISSUE TITLE
Noise estimation map

### ISSUE THREAD

**Issue by jarvislkm** [GuoShi28/CBDNet#1]
Hi, is it possible to show one or two output image of the noise estimation network? For both synthesis image and real world image? Thanks.

**Comment by GuoShi28** [comment]
@jarvislkm Hi, Sorry for getting back to you so late. You can obtain noise estimation by adding the following code in the released test code:
```
noise_est = net.getVarIndex('predictionSigma');
net.vars(net.getVarIndex('predictionSigma')).precious = 1;

run CNN denoiser

est_sigma = squeeze(gather(net.vars(noise_est).value));
```
If you have other suggestions or questions, please feel free to contact me.

**Comment by jarvislkm** [comment]
Thanks, it works.
