### ISSUE TITLE
Question about CRF

### ISSUE THREAD

**Issue by LoSealL** [GuoShi28/CBDNet#11]
Hi, it's an amazing work!
I wonder in your noise model (EQ 3), did you try to train the model with and without CRF? If we train CBDNet without the knowledge of CRF, how much gap will appear in real photo denoising?
I don't find any comparison among EQ 1, 2 and 3.

**Comment by GuoShi28** [comment]
Hi,
Thank you for your interest! I have added some discussion about the function of ISP in noise modeling in the new version of my paper. But I did not discuss the function of CRF, so I am not quite sure the quantitative gap. I think the more perfect you model the ISP process, the better denoising results you can obtain.

**Comment by LoSealL** [comment]
Thanks you:)
And in your paper, you mention a CBDNet-Real, does this means that you train it with ONLY real photo by L_{tv} and disgard L_{asymm}?

**Comment by GuoShi28** [comment]
CBDNet Real only train the network using L2 without estimating the noise estimation loss. The network structure is the same with other comparison networks.

**Comment by LoSealL** [comment]
Thanks a lot. I have no more questions.
