### ISSUE TITLE
Q about CRF_Map and ICRF_Map 

### ISSUE THREAD

**Issue by LoSealL** [GuoShi28/CBDNet#12]
I suppose `CRF_Map` and `ICRF_Map` is somehow reversed (“写反了”） either revered in comments or in callee function `AddNoiseMosai`.

- Detail:
In `CRF_Map` comment, input image (RGB?) and returns L, while in `ICRF_Map` comment, input L and returns image.
But in `AddNoiseMosai`, I believe it inputs image and returns noised image. But it first calls `ICRF_Map` and then calls `CRF_Map` at last.

So I suppose your comment is wrong.

**Comment by GuoShi28** [comment]
@LoSealL Actually, the CRF curve is to transfer L to image RGB. For more details, you can refer to [Here](https://github.com/GuoShi28/CBDNet/blob/master/Other_material/some_introduction_material_of_ISP.md)
