### ISSUE TITLE
Do you train your model with multi-gpus by using matconvnet?

### ISSUE THREAD

**Issue by XSLXANDY** [GuoShi28/CBDNet#14]
I found using 1 single gpu is very time consuming. But I have some trouble using multi-gpus with matconvnet. I wonder if you can show me how to modify the code to adapt multi-gpus settings?

**Comment by GuoShi28** [comment]
I also use only one GPU to train the model and it takes me about 3 days for about 40 epoch. I did not change my code to multi-GPUs. Setting a larger stride size (when cutting training patches from a whole image) is an effective way to save training time but not greatly affect performance.

**Comment by XSLXANDY** [comment]
I got it, thank you!
