### ISSUE TITLE
Why UNet and not continuing Strategies of FFDNet?

### ISSUE THREAD

**Issue by TouqeerAhmad** [GuoShi28/CBDNet#18]
Hi,
Great work and very good effort towards actual denoising instead of celebrating AWGN denoising as many others do :) 
I was curious as to why you did not continue using the strategy used in FFDNet where the image is downscaled to four quarter size images and concatenated with the noise map. 

Why not just replace the noise map (based on AWGN sigma) with the noise map generated by Noise Estimator Network? I was wanting to know if you gave FFDNet architecture a try or otherwise what was the reason to deviate from that towards UNet?

Thank you!

**Comment by GuoShi28** [comment]
Hi, the downsampling method like ffdnet is a great step to accelerating the network. I just not use this in CBDNet and I also think using downsampling is okay.
