### ISSUE TITLE
question about the difference between matlab code and python code of isp process

### ISSUE THREAD

**Issue by PeeBar** [GuoShi28/CBDNet#33]
Thanks for provide the python code of isp process, I just find that you add Poisson-Gaussian noise before mosaic_bayer in the matlab code, but you add the noise after mosaicing and inver white balancing in the python code. Is this difference reasonable?

**Comment by GuoShi28** [comment]
Mosaic can treat as linear pixel sampling. So adding noise before and after this step is the same for the final training data. Adding noise after mosaic_bayer is more explainable.

**Comment by PeeBar** [comment]
Thank you very much.

**Comment by PeeBar** [comment]
Hello! I am sorry to interrupt you again cause I find that there is a small difference between the CRF_Map.m file and the CRF_Map function in python. In the CRF_Map.m file, [comp2=temp-B(index-1)](https://github.com/GuoShi28/CBDNet/blob/724a88cd6af4125afc341b28ed4872004eb37e40/utils/CRF_Map.m#L38), but it becomes to [temp-I_temp(index-1)](https://github.com/GuoShi28/CBDNet/blob/724a88cd6af4125afc341b28ed4872004eb37e40/SomeISP_operator_python/ISP_implement.py#L96) in Python

**Comment by PeeBar** [comment]
Hello! I am sorry to interrupt you again cause I find that there is a small difference between the CRF_Map.m file and the CRF_Map function in python. In the CRF_Map.m file, [comp2=temp-B(index-1)](https://github.com/GuoShi28/CBDNet/blob/724a88cd6af4125afc341b28ed4872004eb37e40/utils/CRF_Map.m#L38), but it becomes to [temp-I_temp(index-1)](https://github.com/GuoShi28/CBDNet/blob/724a88cd6af4125afc341b28ed4872004eb37e40/SomeISP_operator_python/ISP_implement.py#L96) in Python.Can you tell me which one is right?
Thank you!

**Comment by GuoShi28** [comment]
I check the code and find the python code may be right. I update the Matlab code. Thank you for pointing it out. 
![image](https://user-images.githubusercontent.com/19340458/67450036-bcfba080-f64e-11e9-811e-05b4c99fa4d7.png)

**Comment by PeeBar** [comment]
Thanks for your response!
