### ISSUE TITLE
Ground Truth for Noise level

### ISSUE THREAD

**Issue by oracle85** [GuoShi28/CBDNet#5]
Hi,

Thanks a lot for sharing your test code! 

I am trying to re-train using the same approach that you mentioned in the paper. I am not able to understand how the ground truth for the noise level map was generated for synthetic data (from the paper/code).

Can you please explain how you create the ground truth for the noise level map? For e.g., each pixel in the noise level map contains the std. dev. information in RGB domain or something else?

 If you can share the code that would be great as well. 

Thanks,
Tejas

**Comment by GuoShi28** [comment]
Hi, You can refer to another similar issue https://github.com/GuoShi28/CBDNet/issues/4 . If you still have questions, please feel free to contact me.

**Comment by oracle85** [comment]
Thanks for the quick response!
What does "\sigma_c + L\sigma_s " mean?
Is it the same as sigma_c + L*sigma_s

**Comment by GuoShi28** [comment]
Yes. It's the same.

**Comment by oracle85** [comment]
Thanks!
