### ISSUE TITLE
A question about the loss

### ISSUE THREAD

**Issue by XSLXANDY** [GuoShi28/CBDNet#7]
Hello, I noticed you used L2 norm instead of F norm in your paper. 
![image](https://user-images.githubusercontent.com/29296287/47551921-03cc9280-d936-11e8-9fa6-399364dfcde6.png)
![image](https://user-images.githubusercontent.com/29296287/47551955-13e47200-d936-11e8-80c9-f74e290ec835.png)
In the loss function, it seems the variable x and y are matrices because I haven't seen any sum operation.
Notably, with regard to vectors, L2 norm is equal to F norm. But for matrix, L2 norm is totally different from F norm. 
I want to confirm whether you used L2 norm of the matrix because papers often use F norm rather than L2 norm in image denoising. 
Can you help me? Thanks a lot!

**Comment by GuoShi28** [comment]
You are right. I follow the L2 norm experiment setting of other papers.

**Comment by XSLXANDY** [comment]
Thank you very much for your consideration and time.
But I'm still wondering why you choose the trace norm rather than F norm. 
Can you list your reference papers about the L2 norm?

**Comment by GuoShi28** [comment]
I am not sure I understand your question in the right way. preview works, such as [DnCNN](https://github.com/cszn/DnCNN), [FFDNet](https://github.com/cszn/FFDNet) are both using L2 norm. I did not do the experiment with F norm in denoising, so I can not say L2 norm is a better choice. 
There a research discussed the impact of different loss functions in image restoration ([Paper](https://arxiv.org/pdf/1511.08861.pdf)). You can also refer to this paper and see whether its helpful to your understanding.

**Comment by XSLXANDY** [comment]
I know what you mean. I appreciate your assistance very much!
