### ISSUE TITLE
Receptive field

### ISSUE THREAD

**Issue by Shakarim94** [GuoShi28/CBDNet#8]
Hello. What is the receptive field of the denoising network (CNN_d)? My calculations yield 83. I used the info given in the network illustration and the fact that all filters are 3x3 (strided and transpose conv). Is this correct? I assumed that the receptive field would be as large as the training input (128x128)

**Comment by GuoShi28** [comment]
you can refer to the equation in https://github.com/BRML/CNNbasedMedicalSegmentation/issues/2 to calculate the receptive field. In my opinion, the size of training patches should be a little larger than receptive field.

**Comment by Shakarim94** [comment]
Actually I used the same formula, and even checked in this website: https://fomoro.com/tools/receptive-fields/. I just thought the receptive field would be closer to 128. But that paper mentions that larger receptive field doesn't necessarily mean better performance (they themselves have only 73). So now I think this issue can be closed. 

I have one more question though. I wanted to implement a mini version for MNIST or CIFAR10. I am curious about the role of 6 convolutions in the bottom level, I have only seen 2,3 convolutions in bottom level of U-NET before. How do I construct a network for a different dataset and what kind of suggestions do you have for the network architecture?

**Comment by GuoShi28** [comment]
I think using 6 or 2,3 convolutional layers are both okay. If you train on a very small dataset, I prefer to not using a very deep network, such as 60+ layers.

**Comment by xiaoxiaowannote** [comment]
> 你好。去噪网络（CNN_d）的感受野是什么？我的计算结果为 83。我使用了网络插图中给出的信息以及所有过滤器都是 3x3（跨步和转置转换）的事实。它是否正确？我假设感受野和训练输入一样大（128x128）
hello!  i have a trouble with it too ,can you tell me how to calculate it ,thanks !
